# Inferring mRNA from Protein
from collections import Counter
from functools import reduce

s = list('MVDTNCPKNFENQMHVGQRCQYVDTTGWDAERPYVIGMERPSQCESTEEVRWIKIWDQADEQDWIDREHMEREYAECEIENWLFLNMLAIQPMKREVGGELDHMDSYDKCWEPCGYNYNCCYRSQLQVAYPKPAAPSNSVQPMKAVMQDKAEFDANDKPSWQSWWAQHEDETHFQTCQDCKETSFYDCWFTICHYNFPHHACGTLVGTSPIYRYEQFECKKETIAWHSAALSWCIPKRSAEWMVMGWSAAEFQKTAAGSHIMWGHCFNIWTHVGNHCAEWDYPQKSVLKWNDKMCPPTECWMIETLSQDHEKFNIDRQVSSCFWKVLAIADNPIRMYVFTFTRCRLQLQTKQPRYMPIPCLIVIYMQETCQQTIHFGTHIPSWFQGHAWNTAMTLKSNGFGRYIHARGYGMDIYQCAETVAHPLKFIWETVVWSGHNCILEKCIWFCLDAFWDNILIENNVSAAEPHTEWIALEYNWSYVEKLAYALRSCGAYAIYFHPCKYSHNKYMTRHDWCVDAKMDVYSTDACYGNVKKDNTSNTQDRVDEVLTHSGQPGISRWTKRITLYQFNLKVKQVWHCVSMWHEMKYDDAPFEGSHTNEFFTHVVDPWAESHKMEINNLDSCGCYSPKNPSYPTDRFEEFRKELYLPLFAVCSDLPFDWFWCGDHMRGNLEEEGVISNKIQGRNYSNGPGDLWSAGAHNTMEKMRNAACQDDFQTRSSFSAKVAPHPMKKPVLYRVKNMHGMLAKNVCVFAEYQIFWMSWERSQRKKSYCMWWAPEIFEVIYGPQDLSYKDHGHMPFNLEHNSFRLFRCNDATRYMMVSLIHCSPILETECWHGLSTGLVRITVKDREKAHGTMHNKAYNIANCNPEGWDMSNQHRQSGFDSLTSAWRQGMQIHDYSLHPLMLCKQLFCPHGQRYSTTNNDHTFFDESWVMRFIEGIKGESIDSKFPYYVSLNHNNFELGIEFVLLLRNYAMVWNTCDRKYMCYIYIYTMGRGQDLSSA')
s.append('Stop')


# Read codon table file
def get_codon_table(filename):
    codon_table_file = open(filename)
    codon_table = codon_table_file.read()
    codon_list = list(filter(None, codon_table.replace('   ','\n').split('\n'))) # Convert codon table to lookup dictionary
    return dict(map(lambda e: e.split(' '), codon_list))


cdnt = get_codon_table('Data/RNA-codon-table.txt')   # Read codon table into dictionary
rna_cnt_dict = dict(Counter(cdnt.values()).items())  # Count number of keys for a given value and store as dict
rna_cnt = [rna_cnt_dict[x] for x in s]               # Map sample list to the dictionary (list of values)

res = reduce(lambda x, y: x * y , rna_cnt) % 1000000  # Multiply all values in the list with modulo 1M
print(res)

